### ISSUE TITLE
Integration with a theme

### ISSUE THREAD

**Issue by iandstanley** [api-evangelist-tools/spreadsheet-to-yaml-in-jekyll#1]
I noticed that the repo appears to be a jekyll website.

I already have started work on a theme for a website but don't want to throw it away and start from your repo

How much is required from the repo to get it working?

**Comment by kinlane** [comment]
Hi there. It should work as is. You just need to change the ID for the spreadsheet, and pass in your own OAuth token. Its a one page script, not really dependent on the jekyll theme. So create your repo and just copy / paste.  I may spend some time documenting more. Sorry.
